version: '3'

services:
  web:
    image: ghcr.io/chovin/test_github_actions:latest
    environment:
      - VIRTUAL_HOST=${HOST}
      - VIRTUAL_PORT=5000
    networks:
      - proxy-network

  nginx:
    image: nginxproxy/nginx-proxy:latest
    restart: always
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${XDG_RUNTIME_DIR:-/var/run}/docker.sock:/tmp/docker.sock:ro"
    networks:
      - proxy-network

networks:
  proxy-network:
